name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denoland/setup-deno@main
      with:
        deno-version: "1.10.3"
    - name: Lint & fmt
      run: |
        deno fmt --check
        deno lint
    - name: Type check
      run: |
        deno cache --unstable denops/pomodoro/app.ts
    - name: Tests
      run: |
        deno test --unstable --allow-env=DENOPS_TEST_VIM,DENOPS_TEST_NVIM,DENOPS_PATH ./tests
